name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Clean and Build APK with Gradle
      run: |
        # گٹ ہب کلاؤڈ کو ہر حال میں گریڈل فائل ڈھونڈنے میں مدد کرنے کے لیے فولڈرز کی تلاشی
        if [ -d "android" ]; then cd android; fi
        if [ -d "Android" ]; then cd Android; fi
        
        # پرمیشن سیٹ کرنا اور بلڈ رن کرنا
        chmod +x gradlew || true
        ./gradlew clean assembleDebug --stacktrace
        
    - name: Upload Finished APK
      uses: actions/upload-artifact@v4
      with:
        name: Myra-Assistant-APK
        path: "**/build/outputs/apk/debug/*.apk"
